### ISSUE TITLE
[question] how do I set --indent for shfmt

### ISSUE THREAD

**Issue by smartding** [bash-lsp/bash-language-server#1161]
I' m using bash-language-server with neovim. 
I looked through config.ts as suggested by README, but I can't find an option to set `--indent` for shfmt.
The only available options for shfmt are:

1.  binaryNextLine
1. caseIndent
1. funcNextLine
1. path
1. spaceRedirects

**Comment by danelowe** [comment]
Having a look at [onDocumentFormatting](https://github.com/bash-lsp/bash-language-server/blob/2d51e2838033e3c98456345040c24fae96bf6655/server/src/server.ts#L826), `params.options` contains options that controls the indent. 

It looks like that is set when calling the format action, rather than being part of the config. 

If I add an `.editorconfig` file, my neovim formatting seems to respect it. I'm not 100% certain, but I think that might be going into bash-language-server rather than updating the buffer after formatting. There's possibly other ways to set up editors to send this config when calling the LSP formatter.

**Comment by chris-reeves** [comment]
The indentation used for `shfmt` is whatever you've configured for your current editor session. If your editor is configured for two-space indents then that's what it will use. If you're using tabs for indentation then `shfmt` will use that.

`.editorconfig` is an editor-independent way of configuring this for a project. For plain old Vim, the options `shiftwidth` and `expandtab` will control indentation. Having never used NeoVim I couldn't say to what extent those options will work for you.
