### ISSUE TITLE
The GUI application was launched unexpectedly by the VSCode Bash IDE during string completion

### ISSUE THREAD

**Issue by shizhx** [bash-lsp/bash-language-server#1170]
### Code editor

Visual Studio Code

### Platform

Linux x64 6.6.30-2-MANJARO

### Version

Bash IDE v1.41.0

### What steps will reproduce the bug?

Video:

https://github.com/bash-lsp/bash-language-server/assets/7520007/5e0b98d5-5e98-47bf-9101-b511edaa3141

ps:
![image](https://github.com/bash-lsp/bash-language-server/assets/7520007/48677e62-cd1e-40b1-a442-1bd06c5f06ea)

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

Should not launch

### What do you see instead?

the GUI application be launched.

**Comment by shizhx** [comment]
Is there a config to disable getting command options by executing it?

**Comment by mcecode** [comment]
This was already raised in #1116, fixed in 04a2cb3476b786e5ec76d17a737fc852633238b9, and released in bash-language-server version 5.3.3, but the latest VSCode extension is running 5.2.0 so this will probably be fixed when that gets updated.

Is there any chance we can get the fix out to VSCode users too @skovhus?
