### ISSUE TITLE
Unable to Read - Error when jumping to file from reference list

### ISSUE THREAD

**Issue by jkdba** [bash-lsp/bash-language-server#259]
When viewing references of a function, if I double click a reference in a different file instead of navigating to it it fails with:

> Unable to open 'x.sh': Unable to read file '\\c:\dev\git\shell\main\operation\x.sh' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\c:\dev\git\shell\main\operation\x.sh').

appears to be adding a `\\` in front of the path for some reason.

System:

Extension: v1.10.2
Version: 1.47.3 (user setup)
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by zowers** [comment]
have same issue on windows when I have `editor.gotoLocation.multipleDefinitions=goto`
if you switch to `editor.gotoLocation.multipleDefinitions=peek` then the peek window is shown with 2 results where only one with opened `file.sh` is working and second goes to the same `\\c:\file.sh`  path and fails.

**Comment by L0rd3N3gr0** [comment]
Hi,

Same here.

This only happens when the folder where the scripts are is open in the vscode explorer, as can be seen in the attached images.

If the folder is closed in explorer, the second definition (with '\\c\....') does not appear. In this case, clicking with the right mouse button goes straight to the definition of the function or variable.

![image002](https://user-images.githubusercontent.com/98430026/151149055-9986664d-1929-44d6-bdc9-774580d208dc.png)
![image007](https://user-images.githubusercontent.com/98430026/151149047-dee07321-8126-49fd-b1f7-92130add9eb9.png)

**Comment by jfcherng** [comment]
Presuming this has been fixed by https://github.com/bash-lsp/bash-language-server/pull/433.

**Comment by toolpaddz** [comment]
@jfcherng this is not fixed. Would love to see a fix or workaround for this.

**Comment by jfcherng** [comment]
> @jfcherng this is not fixed. Would love to see a fix or workaround for this.

The latest release of Bash IDE doesn't contains [my fix](https://github.com/bash-lsp/bash-language-server/pull/433/files#diff-4c1f558022e743435c3efc9d947a6c651ab4452d9bbd46cd07f7187b96f08746).

![image](https://user-images.githubusercontent.com/6594915/197958858-ec4d271d-a1b1-4941-9cef-5c4d8ec5aab8.png)

If you want, you can manually fix that file on your machine.
On my machine, it's at "C:\Users\jfcherng\.vscode\extensions\mads-hartmann.bash-ide-vscode-1.14.0\node_modules\bash-language-server\out\analyser.js"

I am fairly sure my PR fixes this issue.
