### ISSUE TITLE
Not publishing diagnostics

### ISSUE THREAD

**Issue by minikN** [bash-lsp/bash-language-server#272]
Hello,

in your feature list you list diagnostic reporting as one feature. But are you actually publishing the diagnostics via `textDocument/publishDiagnostics`?

If I log the IO between the server and my editor I don't see any mention of `textDocument/publishDiagnostics` if I create syntax errors in my code and thus not getting any linting. Maybe I'm misunderstanding something.

Cheers.

**Comment by srillia** [comment]
i meet the same issue

**Comment by cambp4** [comment]
same, here so we need to install tree sitter as well ?

**Comment by lelutin** [comment]
I'm also not seeing diagnostics, so I've added them via coc-diagnostics + shellcheck, but it would be great if this language server could publish language diagnostics. fwiw shellcheck is an excellent backend for this since it has syntax check and also lint checks. shellcheck can also make quickfix suggestions when used with json output format that could get published by bash-language-server

**Comment by shabbyrobe** [comment]
I have some changes in my fork here that report diagnostics using shellcheck: https://github.com/shabbyrobe/bash-language-server.

It's early days so I'm still dogfooding it at the moment, but if there's interest I'd be happy to submit a PR and make any necessary changes.

**Comment by shabbyrobe** [comment]
I've been dogfooding this for a bit and it seems to work, @skovhus - would a PR for shellcheck diagnostics integration be welcome?

**Comment by skovhus** [comment]
@shabbyrobe there is some ongoing discussion in https://github.com/bash-lsp/bash-language-server/issues/104 

Let us move the discussion over there, and feel free to create a PR with shellcheck support. 👏
