### ISSUE TITLE
Hovers could show up for bash language constructs

### ISSUE THREAD

**Issue by chrismwendt** [bash-lsp/bash-language-server#50]
It would be helpful if hovering over keywords (`local`, `for`, `while`, etc.) showed some documentation.

**Comment by mads-hartmann** [comment]
Thanks for creating this issue @chrismwendt. We've already implemented this (or tried to 😅) but there seem to be a bug when we try to get the word at the given point. At least  in the following example

```sh
function what {
    local test="test"
    echo ${test}
}

what
```

If you hover over local it thinks the word under the cursor is `local test="test"` rather than `local`. Might have to reconsider the logic for `wordAtPoint`

**Comment by skovhus** [comment]
This is already implemented and latest version works as expected.
