### ISSUE TITLE
Variable hover not working since v1.23

### ISSUE THREAD

**Issue by exh596** [bash-lsp/bash-language-server#670]
Hovering over a variable name throws an error in v1.24 and above. v1.23 works properly.

![image](https://user-images.githubusercontent.com/106156721/211377687-09bd4e42-9925-4da9-8650-3f538d38b553.png)
![image](https://user-images.githubusercontent.com/106156721/211377927-07c6197a-878e-4e6f-9e1c-e6a8948c7eea.png)

**Comment by skovhus** [comment]
Thanks for reporting this. Could you provide a failing code example?

**Comment by skovhus** [comment]
@exh596 is this still the case with the latest extension? If so then I would love to get a code example. Thanks. :)

**Comment by yusufaktepe** [comment]
> @exh596 is this still the case with the latest extension? If so then I would love to get a code example. Thanks. :)

Yes, this is still the case ([example](https://github.com/yusufaktepe/rofi-brbw/blob/master/rofi-brbw)).

**Comment by skovhus** [comment]
Thanks for the example script. It turns out that for files where the treesitter parser fails, we didn't gracefully handle this in the later version of bash-language-server. I believe the error handling in the latest extension (1.30.0) should now solve this case and hovering should work again.

Let me know if it works for you. Or if you have other suggestions for improving the language server.

**Comment by yusufaktepe** [comment]
> Let me know if it works for you.

It seems to be fixed. Thank you for your work.
